name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]
  push:
    branches:
      - main
    paths:
      - '.github/workflows/versioning.yml'

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: get token
        id: token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1
        with:
         app-id: ${{ vars.RELEASER_APP_ID }}
         private-key: ${{ secrets.RELEASER_APP_KEY }}
      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb # v2
        with:
          token: ${{ steps.token.outputs.token }}
