name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]
  push:
    branches:
      - main
    paths:
      - ".github/workflows/versioning.yml"

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-24.04
    steps:
      - name: get token
        id: token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ vars.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_APP_KEY }}
      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb # v2
        with:
          token: ${{ steps.token.outputs.token }}
